// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9kRrhKxxuoCs27_-MI7rtj6hAB6MMrnc',
    appId: '1:593581842078:web:897a5a5f94f4d462bba58f',
    messagingSenderId: '593581842078',
    projectId: 'flutter-chat-app-2025-178a5',
    authDomain: 'flutter-chat-app-2025-178a5.firebaseapp.com',
    databaseURL: 'https://flutter-chat-app-2025-178a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-2025-178a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRNIvGmEW0adWwsoFnmRjK90vGKz6yWds',
    appId: '1:593581842078:android:fa30748eb5d32757bba58f',
    messagingSenderId: '593581842078',
    projectId: 'flutter-chat-app-2025-178a5',
    databaseURL: 'https://flutter-chat-app-2025-178a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-2025-178a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCrfdg-xgqN6ey-vR9BzKgZ2ljO6ohBjg',
    appId: '1:593581842078:ios:8010ad3951de0892bba58f',
    messagingSenderId: '593581842078',
    projectId: 'flutter-chat-app-2025-178a5',
    databaseURL: 'https://flutter-chat-app-2025-178a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-2025-178a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCrfdg-xgqN6ey-vR9BzKgZ2ljO6ohBjg',
    appId: '1:593581842078:ios:8010ad3951de0892bba58f',
    messagingSenderId: '593581842078',
    projectId: 'flutter-chat-app-2025-178a5',
    databaseURL: 'https://flutter-chat-app-2025-178a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-2025-178a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9kRrhKxxuoCs27_-MI7rtj6hAB6MMrnc',
    appId: '1:593581842078:web:74c07f072e3aae97bba58f',
    messagingSenderId: '593581842078',
    projectId: 'flutter-chat-app-2025-178a5',
    authDomain: 'flutter-chat-app-2025-178a5.firebaseapp.com',
    databaseURL: 'https://flutter-chat-app-2025-178a5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-2025-178a5.firebasestorage.app',
  );
}
